# Change EXPERIMENT when initializing a new repo for an experiment
expNumber: cxi101342025 # Enter the full run number here, e.g. cxil1037623.
expDir: /sdf/data/lcls/ds/cxi/cxi101342025/ # Full path to the experimental directory here e.g/ /sdf/data/lcls/ds/cxi/cxil1037623/.

data_paths:
  - runs: [0, .inf] # Add the range of runs that this path applies for. yaml parses .inf to float('inf') in python.
    # path: /sdf/data/lcls/ds/cxi/cxi101342025/hdf5/smalldata/ # Add the full data path here.
    path: /sdf/data/lcls/ds/cxi/cxi101342025/hdf5/smalldata/
# Add more data locations for specific runs if need be like this:
#  - runs: [20, 30]
#    path: /path/to/another/location/

photon_energy:
  - runs: [0, .inf]
    energy: 10 # in keV

samples:
  - runs: [0, 1]
    sample: 'Dark'

# Other user information and configurations shared across analysis notebooks can go here, or above. Whatever floats your boat.
